language: php

matrix:
    include:
        - php: 7.2
          env: ECS=true TWEET=true
        - php: 7.2
          env: PHPSTAN=true
        - php: 7.2
          env: PHPUNIT_FLAGS="--coverage-clover coverage.xml"
        - php: 7.2
          env: FRONT_END=true

install:
    - composer install

script:
    - if [[ $FRONT_END == true ]]; then composer build-assets; fi

    # run tests for tested posts (with "tested: true" in header configuration)
    - vendor/bin/phpunit $PHPUNIT_FLAGS
    # check code standard (defined in composer.json "scripts" section)
    - if [[ $ECS == true ]]; then composer check-cs; fi
    - if [[ $PHPSTAN == true ]]; then composer phpstan; fi
    # test that website is generated
    - vendor/bin/statie generate source

    # tweets posts
    - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" && $TWEET != "" ]]; then vendor/bin/publish-new-tweet; fi

after_script:
    - |
        if [ "$PHPUNIT_FLAGS" != "" ]; then
            wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
            php coveralls.phar --verbose --config tests/.coveralls.yml
        fi

# see https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: output
    on:
        branch: master

# do not send success notifications, they have no value
notifications:
    email:
        on_success: never
